version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com
      - REPOSITORY_URI=${ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/${PROJECT}

  build:
    commands:
       - echo Build started on `date`
       - echo Building the Docker image...  
       - cd ${PROJECT}/${VERSION}
       - echo IMAGE_TAG=${VERSION}
       - docker build -t $REPOSITORY_URI:${VERSION} .
  
  post_build:
     commands:
       - echo Build completed on `date`
       - echo Pushing the Docker images...
       - docker push $REPOSITORY_URI:${VERSION}
